Update the README
nextbitlabs/ebs-cargo pull request #10
Opened 2018-10-22 12:42 UTC by rpadovani

Add some useful info in the README

2018-10-22 13:27 UTC, alessandrobessi requested changes

2018-10-22 13:27 UTC, alessandrobessi commented on README.md
> +**BE CAREFUL USING IT WITH ALREADY EXISTING EBS VOLUME, DATA CAN BE LOST**
volumeS

2018-10-22 13:27 UTC, alessandrobessi commented on README.md
> +When you want to load data on a new EBS volume, lot of operations have to be done: logging in AWS, creating a volume, creating an instance, attaching the volume, formatting it, mounting it, download
a lot or lots

2018-10-22 13:27 UTC, alessandrobessi commented on README.md
> +When you want to load data on a new EBS volume, lot of operations have to be done: logging in AWS, creating a volume, creating an instance, attaching the volume, formatting it, mounting it, download
downloading

2018-10-22 13:27 UTC, alessandrobessi commented on README.md
> +Wouldn't be simple just having to launch a command indicating which local directory you want to upload?
simple -> easier?

2018-10-22 13:27 UTC, alessandrobessi commented on README.md
> +You can see all the possible options using:
possible -> available?

2018-10-22 13:43 UTC, lucagrementieri requested changes

2018-10-22 13:43 UTC, lucagrementieri commented on README.md
> +**BE CAREFUL USING IT WITH ALREADY EXISTING EBS VOLUME, DATA CAN BE LOST**
What happens if you run it on an already existing volume?
Maybe you should specify it. I think the user expects that the directory will be copied on the existing volume.

2018-10-24 08:16 UTC, rpadovani commented on README.md
> +**BE CAREFUL USING IT WITH ALREADY EXISTING EBS VOLUME, DATA CAN BE LOST**
Done

2018-10-24 08:22 UTC, rpadovani commented on README.md
> +Wouldn't be simple just having to launch a command indicating which local directory you want to upload?
Done

2018-10-24 08:22 UTC, rpadovani commented on README.md
> +When you want to load data on a new EBS volume, lot of operations have to be done: logging in AWS, creating a volume, creating an instance, attaching the volume, formatting it, mounting it, download
Done

2018-10-24 08:22 UTC, rpadovani commented on README.md
> +You can see all the possible options using:
Done

2018-10-24 08:24 UTC, alessandrobessi approved these changes

2018-10-24 08:28 UTC, lucagrementieri approved these changes

2018-10-24 08:28 UTC, merged